### ISSUE TITLE
v5版本使用swow发生文件不存在异常

### ISSUE THREAD

**Issue by etjson** [walkor/workerman#1013]
v5版本使用swow时，每次首次启动或者当发生文件发生变化时，出现如下异常，等待几秒后会恢复正常

```php
ErrorException: require_once(/www/webman/app/index/controller/IndexController.php): Failed to open stream: No such file or directory in /www/webman/vendor/workerman/webman-framework/src/App.php:783
Stack trace:
#0 /www/webman/vendor/workerman/webman-framework/src/App.php(783): support\App::{closure}(2, 'require_once(/w...', '/www/webman/ven...', 783)
#1 /www/webman/vendor/workerman/webman-framework/src/App.php(783): require_once()
#2 /www/webman/vendor/workerman/webman-framework/src/App.php(736): Webman\App::getController('app\\index\\contr...')
#3 /www/webman/vendor/workerman/webman-framework/src/App.php(716): Webman\App::getControllerAction('app\\index\\contr...', 'index')
#4 /www/webman/vendor/workerman/webman-framework/src/App.php(672): Webman\App::guessControllerAction(Array, 'index', 'Controller', '')
#5 /www/webman/vendor/workerman/webman-framework/src/App.php(153): Webman\App::parseControllerAction('/index')
#6 /www/webman/vendor/workerman/workerman/src/Connection/TcpConnection.php(710): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))
#7 /www/webman/vendor/workerman/workerman/src/Events/Swow.php(159): Workerman\Connection\TcpConnection->baseRead(Resource id #134)
#8 [internal function]: Workerman\Events\Swow->Workerman\Events\{closure}()
#9 {main}
```

**Comment by etjson** [comment]
composer:

```text
composer/semver              3.4.0         Semver library that offers utilities, version constraint parsing and validation.
doctrine/annotations         1.14.3        Docblock Annotations Parser
doctrine/deprecations        1.1.3         A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.
doctrine/lexer               2.1.1         PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
laravel/serializable-closure v1.3.3        Laravel Serializable Closure provides an easy and secure way to serialize closures in PHP.
monolog/monolog              2.9.2         Sends your logs to files, sockets, inboxes, databases and various web services
nikic/fast-route             v1.3.0        Fast request router for PHP
php-di/invoker               2.3.4         Generic and extensible callable invoker
php-di/php-di                6.4.0         The dependency injection container for humans
php-di/phpdoc-reader         2.2.1         PhpDocReader parses @var and @param values in PHP docblocks (supports namespaced class names with the same resolution rules as PHP)
psr/cache                    3.0.0         Common interface for caching libraries
psr/container                1.1.2         Common Container Interface (PHP FIG PSR-11)
psr/http-client              1.0.3         Common interface for HTTP clients
psr/http-factory             1.0.2         Common interfaces for PSR-7 HTTP message factories
psr/http-message             2.0           Common interface for HTTP messages
psr/log                      3.0.0         Common interface for logging libraries
swow/swow                    v1.4.1        Coroutine-based multi-platform support engine with a focus on concurrent I/O
workerman/webman-framework   v1.5.16       High performance HTTP Service Framework.
workerman/workerman          v5.0.0-beta.7 An asynchronous event driven PHP framework for easily building fast, scalable network applications.
```

**Comment by etjson** [comment]
文件确定存在，别的驱动没问题，那估计是swow的问题
