### ISSUE TITLE
CaptchaBuilder无法找到字体

### ISSUE THREAD

**Issue by kingchun** [walkor/workerman#1056]
```
ErrorException: imagettfbbox(): Could not find/open font in webman\vendor\webman\captcha\src\CaptchaBuilder.php:352
Stack trace:
#0 [internal function]: support\App::{closure}()
#1 webman\vendor\webman\captcha\src\CaptchaBuilder.php(352): imagettfbbox()
#2 webman\vendor\webman\captcha\src\CaptchaBuilder.php(466): Webman\Captcha\CaptchaBuilder->writePhrase()
#3 webman\plugin\admin\app\controller\AccountController.php(199): Webman\Captcha\CaptchaBuilder->build()
#4 webman\vendor\workerman\webman-framework\src\App.php(319): plugin\admin\app\controller\AccountController->captcha()
#5 webman\vendor\workerman\webman-framework\src\App.php(351): Webman\App::Webman\{closure}()
#6 webman\plugin\admin\app\middleware\AccessControl.php(47): Webman\App::Webman\{closure}()
#7 webman\vendor\workerman\webman-framework\src\App.php(341): plugin\admin\app\middleware\AccessControl->process()
#8 webman\vendor\workerman\webman-framework\src\App.php(141): Webman\App::Webman\{closure}()
#9 webman\vendor\workerman\workerman\Connection\TcpConnection.php(646): Webman\App->onMessage()
#10 webman\vendor\workerman\workerman\Events\Select.php(311): Workerman\Connection\TcpConnection->baseRead()
#11 webman\vendor\workerman\workerman\Worker.php(1488): Workerman\Events\Select->loop()
#12 webman\vendor\workerman\workerman\Worker.php(1405): Workerman\Worker::forkWorkersForWindows()
#13 webman\vendor\workerman\workerman\Worker.php(560): Workerman\Worker::forkWorkers()
#14 webman\vendor\workerman\webman-framework\src\support\App.php(131): Workerman\Worker::runAll()
#15 webman\start.php(4): support\App::run()
#16 {main}
```
字体都是存在的就是报错
Workerman version:4.1.15          PHP version:8.0.2

**Comment by kingchun** [comment]
原来是路径不能有中文
