### ISSUE TITLE
status失效

### ISSUE THREAD

**Issue by wwng2333** [walkor/Workerman#146]
```[XZB /opt/tz]# php tz.php start -d
Workerman[tz.php] start in DAEMON mode
----------------------- WORKERMAN -----------------------------
Workerman version:3.3.9          PHP version:7.1.2
------------------------ WORKERS -------------------------------
user          worker        listen               processes status
root          Proberv       http://0.0.0.0:2345   3         [OK] 
----------------------------------------------------------------
Input "php tz.php stop" to quit. Start success.

[XZB /opt/tz]# ls
_opt_tz_tz.php.pid  online.json         tz.php              vendor              workerman.log
[XZB /opt/tz]# php tz.php status
Workerman[tz.php] status 
[XZB /opt/tz]# php tz.php status
Workerman[tz.php] status 
Workerman[tz.php] not run
[XZB /opt/tz]# php tz.php status
Workerman[tz.php] status 
Workerman[tz.php] not run
```
实际上运行正常

**Comment by walkor** [comment]
ps aux 
看下workerman进程有几个

**Comment by wwng2333** [comment]
```
[XZB /opt/bin]# ps | grep WorkerMan
 5974 admin     1592 S    grep WorkerMan
21084 admin     8592 S    {php} WorkerMan: worker process  Proberv http://0.0.0.0:2345
21085 admin     8592 S    {php} WorkerMan: worker process  Proberv http://0.0.0.0:2345
21086 admin     8592 S    {php} WorkerMan: worker process  Proberv http://0.0.0.0:2345
```
3个

**Comment by walkor** [comment]
应该是 php 7.1.2 信号处理有bug导致的，
换个php版本试下

**Comment by wwng2333** [comment]
```
[XZB /opt/tz]# php5 tz.php start -d
Workerman[tz.php] start in DAEMON mode
----------------------- WORKERMAN -----------------------------
Workerman version:3.3.9          PHP version:5.6.30
[XZB /opt/tz]# ------------------------ WORKERS -------------------------------
user          worker        listen               processes status
root          Proberv       http://0.0.0.0:2345   3         [OK] 
----------------------------------------------------------------
Input "php tz.php stop" to quit. Start success.

[XZB /opt/tz]# php5 tz.php status
Workerman[tz.php] status 
[XZB /opt/tz]# php5 tz.php status
Workerman[tz.php] status 
Workerman[tz.php] not run
[XZB /opt/tz]# uname -a
Linux XZB 3.4.113 #5 SMP Mon Feb 20 22:37:44 CST 2017 mips GNU/Linux
```

**Comment by walkor** [comment]
```php5 tz.php start -d```  ps aux 后找到主进程pid，
然后```strace -p 主进程pid```。

再另外开一个终端，运行 ```php5 tz.php status```
贴下strace的结果。

**Comment by wwng2333** [comment]
```
[XZB /opt/home/admin]# strace -p 3703
strace: Process 3703 attached
wait4(-1, 0x7f90e1d8, WSTOPPED, NULL)   = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGUSR2 {si_signo=SIGUSR2, si_code=SI_USER, si_pid=3712, si_uid=0} ---
sigreturn({mask=[]})                    = -1 EINTR (Interrupted system call)
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 16) = 0
umask(000)                              = 000
lseek(3, 0, SEEK_SET)                   = 0
write(3, "", 0)                         = 0
close(3)                                = 0
close(2)                                = 0
close(1)                                = 0
close(4)                                = 0
close(0)                                = 0
munmap(0x76e7a000, 266240)              = 0
munmap(0x76ec5000, 1052672)             = 0
munmap(0x76fc6000, 266240)              = 0
brk(0xdfb000)                           = 0xdfb000
exit_group(0)                           = ?
+++ exited with 0 +++
```
`php5 tz.php status`后主进程就消失了

**Comment by walkor** [comment]
第一次见到这种情况，
是否有改动过Workerman代码？

**Comment by wwng2333** [comment]
并没有改过
刚才重新下了一份`https://github.com/walkor/Workerman/archive/v3.3.9.zip`
还是一样

**Comment by walkor** [comment]
tz.php 代码能发一下么？

**Comment by wwng2333** [comment]
https://github.com/wwng2333/tz

**Comment by walkor** [comment]
我这里试了mac 系统 和 ubuntu都是没问题的。
要排查这个问题 需要你打日志了，
https://github.com/walkor/Workerman/blob/master/Worker.php#L774
status 会进入这个分支，可以打印下日志看看在走到哪里退出的。

**Comment by wwng2333** [comment]
```
[XZB /opt/tz]# tail -10 workerman.log 
2017-02-25 16:10:23 pid:3730 Workerman[tz.php] status 
2017-02-25 16:16:10 pid:3736 Workerman[tz.php] status 
2017-02-25 16:16:10 pid:3736 Workerman[tz.php] not run
2017-02-25 16:16:13 pid:3737 Workerman[tz.php] stop 
2017-02-25 16:16:13 pid:3737 Workerman[tz.php] not run
2017-02-25 16:16:19 pid:3740 Workerman[tz.php] start in DAEMON mode
2017-02-25 16:16:19 pid:3743 Warning: User root not exsits
2017-02-25 16:16:19 pid:3745 Warning: User root not exsits
2017-02-25 16:16:19 pid:3744 Warning: User root not exsits
2017-02-25 16:16:33 pid:3749 Workerman[tz.php] status 
```
日志指的是这个吗

**Comment by walkor** [comment]
不是这个意思。因为我这里无法重现问题，需要你自己动手找到执行到了程序的哪个部分出现问题并退出了。
你可以在我说的那个位置开始排查，比如把在怀疑有问题的地方自己记录下日志，
最简单的比如在怀疑有问题的地方 echo 一段文字比如行号，启动的时候不加-d 也就是debug方式启动，再启动一个终端运行status, 如果程序执行到了你echo 的位置就会有打印，没执行到就不会打印，最终能定位到在哪一个地方退出的

**Comment by wwng2333** [comment]
明白了 我现在去排查

**Comment by wwng2333** [comment]
按照您的方法，获得报错如下：
```
[XZB /opt/tz]# php tz.php start
Workerman[tz.php] start in DEBUG mode
Warning: User root not exsits
----------------------- WORKERMAN -----------------------------
Warning: User root not exsits
Workerman version:3.3.9          PHP version:7.1.2
------------------------ WORKERS -------------------------------
user          worker        listen               processes status
root          Proberv       http://0.0.0.0:2345   3         [OK] 
----------------------------------------------------------------
Press Ctrl-C to quit. Start success.
Warning: User root not exsits

Fatal error: Uncaught Error: Call to undefined function Workerman\sys_getloadavg() in /opt/tz/vendor/Worker.php:1213
Stack trace:
#0 /opt/tz/vendor/Worker.php(774): Workerman\Worker::writeStatisticsToStatusFile()
#1 [internal function]: Workerman\Worker::signalHandler(17, Array)
#2 /opt/tz/vendor/Worker.php(1022): pcntl_signal_dispatch()
#3 /opt/tz/vendor/Worker.php(434): Workerman\Worker::monitorWorkers()
#4 /opt/tz/tz.php(1104): Workerman\Worker::runAll()
#5 {main}
  thrown in /opt/tz/vendor/Worker.php on line 1213
```

**Comment by walkor** [comment]
了解了，感谢反馈

**Comment by wwng2333** [comment]
```php
if(!function_exists('sys_getloadavg')) {
	function sys_getloadavg()
	{
		$loadavg = explode(' ', file_get_contents('/proc/loadavg'));
		for($i=0;$i<3;$i++) {
			$__loadavg[] = $loadavg[$i];
		}
		return $__loadavg;
	}
}
```
这样就可以了

**Comment by sudevva** [comment]
I'm sorry.
My native language is not english too. But please use english, that can help other people to understand each other. Thanks)

**Comment by walkor** [comment]
Good advice. 👍
