### ISSUE TITLE
Uncaught Exception: Could not gather sufficient random data

### ISSUE THREAD

**Issue by wwng2333** [walkor/Workerman#150]
```bash
root@ubuntu:~/tz# php tz.php start
Workerman[tz.php] start in DEBUG mode

Fatal error: Uncaught Exception: Could not gather sufficient random data in /root/tz/vendor/Protocols/Http.php:573
Stack trace:
#0 /root/tz/vendor/Protocols/Http.php(573): session_start()
#1 /root/tz/vendor/Protocols/Http.php(577): Workerman\Protocols\HttpCache::init()
#2 /root/tz/vendor/Autoloader.php(60): require_once('/root/tz/vendor...')
#3 [internal function]: Workerman\Autoloader::loadByNamespace('Workerman\\Proto...')
#4 [internal function]: spl_autoload_call('Workerman\\Proto...')
#5 /root/tz/vendor/Worker.php(1421): class_exists('\\Workerman\\Prot...')
#6 /root/tz/vendor/Worker.php(533): Workerman\Worker->listen()
#7 /root/tz/vendor/Worker.php(428): Workerman\Worker::initWorkers()
#8 /root/tz/tz.php(1170): Workerman\Worker::runAll()
#9 {main}

Next Exception: Could not gather sufficient random data in /root/tz/vendor/Protocols/Http.php:573
Stack trace:
#0 /root/tz/vendor/Protocols/Http.php(573): session_start()
#1 /root/tz/vendor/Protocols/Http.php(577): Workerman\Protocols\HttpCache::init()
#2 /root/tz/vendor/Au in /root/tz/vendor/Protocols/Http.php on line 573
root@ubuntu:~/tz# 
```

**Comment by wwng2333** [comment]
after rebuild php in local machine, it works.

**Comment by wwng2333** [comment]
seems it's about kernel version
it works under 4.4.0-63
