### ISSUE TITLE
Error on start WebSocket

### ISSUE THREAD

**Issue by amin0256** [walkor/Workerman#198]
Hi,
I cant use from this library,
When i start using from web socket ( connect to this web server from a JS file ), this error occurred:
```

Exception 'ArgumentCountError' with message 'Too few arguments to function PHPSocketIO\Engine\Engine::dealWebSocketConnect(), 3 passed and exactly 4 expected'

in /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Engine.php:264

Stack trace:
#0 [internal function]: PHPSocketIO\Engine\Engine->dealWebSocketConnect(NULL, true, Object(PHPSocketIO\Engine\Protocols\Http\Request))
#1 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Engine.php(142): call_user_func(Array, NULL, true, Object(PHPSocketIO\Engine\Protocols\Http\Request))
#2 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Engine.php(133): PHPSocketIO\Engine\Engine->checkRequest(Object(PHPSocketIO\Engine\Protocols\Http\Request), Array)
#3 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Engine.php(261): PHPSocketIO\Engine\Engine->verify(Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response), true, Array)
#4 [internal function]: PHPSocketIO\Engine\Engine->onWebSocketConnect(Object(Workerman\Connection\TcpConnection), Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response))
#5 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Protocols/WebSocket/RFC6455.php(283): call_user_func_array(Array, Array)
#6 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Protocols/WebSocket.php(84): PHPSocketIO\Engine\Protocols\WebSocket\RFC6455::dealHandshake(Object(Workerman\Connection\TcpConnection), Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response))
#7 /home/vagrant/Code/dongiPal/vendor/workerman/phpsocket.io/src/Engine/Protocols/SocketIO.php(38): PHPSocketIO\Engine\Protocols\WebSocket::dealHandshake(Object(Workerman\Connection\TcpConnection), Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response))
#8 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Connection/TcpConnection.php(444): PHPSocketIO\Engine\Protocols\SocketIO::input('GET /socket.io/...', Object(Workerman\Connection\TcpConnection))
#9 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #78)
#10 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Events/Select.php(286): call_user_func_array(Array, Array)
#11 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Worker.php(1578): Workerman\Events\Select->loop()
#12 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Worker.php(966): Workerman\Worker->run()
#13 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Worker.php(929): Workerman\Worker::forkOneWorker(Object(Workerman\Worker))
#14 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Worker.php(1082): Workerman\Worker::forkWorkers()
#15 /home/vagrant/Code/dongiPal/vendor/workerman/workerman/Worker.php(433): Workerman\Worker::monitorWorkers()
#16 /home/vagrant/Code/dongiPal/components/Worker.php(17): Workerman\Worker::runAll()
#17 /home/vagrant/Code/dongiPal/commands/ChatController.php(152): app\components\Worker::runAll()
#18 [internal function]: app\commands\ChatController->actionIndex('start')
#19 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#21 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#22 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#23 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('chat', Array)
#24 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('chat', Array)
#25 /home/vagrant/Code/dongiPal/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#26 /home/vagrant/Code/dongiPal/yii(20): yii\base\Application->run()
#27 {main}
Worker[2067] process terminated with exit()/die(). Please do not call exit()/die() in workerman.
worker[PHPSocketIO:2067] exit with status 256
```

code: 

```
$io = new SocketIO(2021);
$io->on('connection', function($socket)use($io){
$socket->addedUser = false;
});
Worker::runAll();
```

and for work with Yii2 framework, i Have write this method and use from this Worker: 
```
<?php
namespace app\components;

class Worker extends \Workerman\Worker{

    /**
     * @inheritdoc
     */
    public static function runAll()
    {
        global $argv;
        if ($argv[0] == 'yii' || $argv[0] == './yii') $argv = array_slice($argv, 1);
        if (isset($argv[2]) && $argv[2] == 'daemon') {
            $argv[2] = '-d';
        }

        parent::runAll();
    }
}
```

do you have any idea ? 
thanks for helping.
sorry for my bad language.

**Comment by walkor** [comment]
I closed this issue because this is not workerman's issue but phpsocket.io‘s.
Please go to https://github.com/walkor/phpsocket.io/issues and create a new issue.
