### ISSUE TITLE
Call to undefined function Workerman\pcntl_signal()

### ISSUE THREAD

**Issue by Ildar5** [walkor/Workerman#427]
hi, when I am trying to start it, I am getting an error 
```
Fatal error: Uncaught Error: Call to undefined function Workerman\pcntl_signal() in /Applications/MAMP/htdocs/site/vendor/workerman/workerman/Worker.php:1058
Stack trace:
#0 /Applications/MAMP/htdocs/site/vendor/workerman/workerman/Worker.php(505): Workerman\Worker::installSignal()
#1 /Applications/MAMP/htdocs/site/worker.php(40): Workerman\Worker::runAll()
#2 {main}
  thrown in /Applications/MAMP/htdocs/site/vendor/workerman/workerman/Worker.php on line 1058
```

Help me please!

**Comment by walkor** [comment]
Please install pcntl extension for php.
