### ISSUE TITLE
Error: class 'Timer' not found

### ISSUE THREAD

**Issue by DeltaVetal26** [walkor/Workerman#449]
Hi, 

I have use Timer for WebSocket server.

My code:
```php
require_once __DIR__ . '/autoload.php';
use Workerman\Worker;

// SSL context.
$context = array(
    'ssl' => array(
        'local_cert'  => 'ssl/server.pem',
        'local_pk'    => 'ssl/server.key',
        'verify_peer' => false,
    )
);

// Create a Websocket server
$ws_worker = new Worker("websocket://0.0.0.0:2342", $context);

// 4 processes
$ws_worker->count = 4;

// SSL Protocol
$ws_worker->transport = 'ssl';

$ws_worker->onWorkerStart = function($ws_worker) {
    $time_interval = 5;
    $timer_id = Timer::add($time_interval,
        function() use ($ws_worker)
        {
            foreach($ws_worker->connections as $connection) {
                $connection->send('text');
            }
        }
    );
};

// Emitted when new connection come
$ws_worker->onConnect = function($connection)
{
    echo "New connection\n";
};

// Emitted when data received
$ws_worker->onMessage = function($connection, $data)
{
    // Send hello $data
    $connection->send('hello ' . $data);
};

// Emitted when connection closed
$ws_worker->onClose = function($connection)
{
    echo "Connection closed\n";
};

// Run worker
Worker::runAll();
```

Error:
```txt
Error: Class 'Timer' not found in /root/vendor/test_server.php:25
Stack trace:
#0 [internal function]: {closure}(Object(Workerman\Worker))
#1 /root/vendor/workerman/workerman/Worker.php(2342): call_user_func(Object(Clos                                                        ure), Object(Workerman\Worker))
#2 /root/vendor/workerman/workerman/Worker.php(1488): Workerman\Worker->run()
#3 /root/vendor/workerman/workerman/Worker.php(1318): Workerman\Worker::forkOneW                                                        orkerForLinux(Object(Workerman\Worker))
#4 /root/vendor/workerman/workerman/Worker.php(1292): Workerman\Worker::forkWork                                                        ersForLinux()
#5 /root/vendor/workerman/workerman/Worker.php(1622): Workerman\Worker::forkWork                                                        ers()
#6 /root/vendor/workerman/workerman/Worker.php(1571): Workerman\Worker::monitorW                                                        orkersForLinux()
#7 /root/vendor/workerman/workerman/Worker.php(511): Workerman\Worker::monitorWo                                                        rkers()
#8 /root/vendor/test_server.php(55): Workerman\Worker::runAll()
#9 {main}
```

Any ideas?

**Comment by walkor** [comment]
add codes `use Workerman\Lib\Timer;`
