### ISSUE TITLE
Exit with status 65280 for unix sockets after update from 3.5.19

### ISSUE THREAD

**Issue by VladimirMerk** [walkor/Workerman#502]
Hello!
After the update, if the server uses sockets and the number of workers is more than one, then this causes a Fatal error with an exit status of 65280

Workerman version:3.5.22
PHP version:7.3.8
event-loop:\Workerman\Events\Event

This code works without errors:
```
use \Workerman\Worker;

require_once __DIR__ . '/../vendor/autoload.php';

$worker = new \Workerman\Worker('unix:///tmp/sock.sock');

$worker->count = 1;

\Workerman\Worker::runAll();
```

This code is causing an error:
```
use \Workerman\Worker;

require_once __DIR__ . '/../vendor/autoload.php';

$worker = new \Workerman\Worker('unix:///tmp/sock.sock');

$worker->count = 2;

\Workerman\Worker::runAll();
```

```
Fatal error: Uncaught Exception in /var/www/vendor/workerman/workerman/Worker.php:2229
Stack trace:
#0 /var/www/vendor/workerman/workerman/Worker.php(1462): Workerman\Worker->listen()
#1 /var/www/vendor/workerman/workerman/Worker.php(1323): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#2 /var/www/vendor/workerman/workerman/Worker.php(1297): Workerman\Worker::forkWorkersForLinux()
#3 /var/www/vendor/workerman/workerman/Worker.php(1614): Workerman\Worker::forkWorkers()
#4 /var/www/vendor/workerman/workerman/Worker.php(1563): Workerman\Worker::monitorWorkersForLinux()
#5 /var/www/vendor/workerman/workerman/Worker.php(512): Workerman\Worker::monitorWorkers()
#6 /var/www/public/test.php(56): Workerman\Worker::runAll()
#7 {main}
  thrown in /var/www/vendor/workerman/workerman/Worker.php on line 2229
Workerman[test.php] stopping ...
worker[AuthWorker:26368] exit with status 65280
Workerman[test.php] has been stopped
```

**Comment by walkor** [comment]
Try to add codes `$worker->reusePort = false;` for unix socket. For example.
```php
$worker = new \Workerman\Worker('unix:///tmp/sock.sock');
$worker->count = 2;
// == Add this ==
$worker->reusePort = false;
```

This already fixed by in master branch which not released.

**Comment by VladimirMerk** [comment]
It helped, thanks

**Comment by lianchengtong** [comment]
i have meet the same issue , the version is Workerman version:4.0.6 , PHP version:7.3.18,what is the trouble?

**Comment by ersunnyroy** [comment]
![image](https://user-images.githubusercontent.com/15190121/88764363-76654480-d192-11ea-934c-9ae5e77a7671.png)
Getting this issue please help

**Comment by ersunnyroy** [comment]
It says process terminated exit with status 65280

**Comment by ersunnyroy** [comment]
I am running it on tcp 3000 port
