### ISSUE TITLE
timer worker process terminated after call shell_exec or exec

### ISSUE THREAD

**Issue by lanlin** [walkor/Workerman#579]
```
use \Workerman\Worker;
use \Workerman\Lib\Timer;

$task = new Worker();
$task->count = 1;
$task->onWorkerStart = function($task)
{
    Timer::add(3, function()
    {
        shell_exec("echo 123456");
    });
};

Worker::runAll();
```

```
#0 foo/vendor/Workerman/Workerman/Events/Select.php(232): {closure}(2, 'call_user_func_...', '...', 232, Array)
#1 foo/vendor/Workerman/Workerman/Events/Select.php(281): Workerman\Events\Select->tick()
#2 foo/vendor/Workerman/Workerman/Worker.php(2430): Workerman\Events\Select->loop()
#3 foo/vendor/Workerman/Workerman/Worker.php(1555): Workerman\Worker->run()
#4 foo/vendor/Workerman/Workerman/Worker.php(1385): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#5 foo/vendor/Workerman/Workerman/Worker.php(1359): Workerman\Worker::forkWorkersForLinux()
#6 foo/vendor/Workerman/Workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#7 foo/start.php(119): Workerman\Worker::runAll()
#8 {main}
Worker[2900] process terminated
```

**Comment by walkor** [comment]
It works fine for me.

Run the following script to see if there is any error output.
```php
<?php
ini_set('display_errors','on');
error_reporting(E_ALL); 
shell_exec("echo 123456");
```

**Comment by lanlin** [comment]
@walkor thanks, you're right. it's nothing about the `shell_exec `, some other error causes it.
