### ISSUE TITLE
Failure running on a read-only filesystem

### ISSUE THREAD

**Issue by cayolblake** [walkor/workerman#821]
Hello @walkor 

Attempting to run on a read only filesystem fails as follows.

```
fopen(/home/dev1/proj1/vendor/workerman/workerman/../_home_dev1_proj1_test.php.pid.lock): Failed to open stream: Read-only file system in file /home/dev1/proj1/vendor/workerman/workerman/Worker.php on line 640

Workerman[/home/dev1/proj1/test.php] start in DEBUG mode

file_put_contents(/home/dev1/proj1/vendor/workerman/workerman/../workerman.log): Failed to open stream: Read-only file system in file /home/dev1/proj1/vendor/workerman/workerman/Worker.php on line 2156

file_put_contents(/home/dev1/proj1/vendor/workerman/workerman/../_home_dev1_proj1_test.php.pid): Failed to open stream: Read-only file system in file /home/dev1/proj1/vendor/workerman/workerman/Worker.php on line 1324

PHP Fatal error:  Uncaught Exception: can not save pid to /home/dev1/proj1/vendor/workerman/workerman/../_home_dev1_proj1_test.php.pid in /home/dev1/proj1/vendor/workerman/workerman/Worker.php:1325

Stack trace:
#0 /home/dev1/proj1/vendor/workerman/workerman/Worker.php(556): Workerman\Worker::saveMasterPid()
#1 /home/dev1/proj1/test.php(31): Workerman\Worker::runAll()
#2 {main}
  thrown in /home/dev1/proj1/vendor/workerman/workerman/Worker.php on line 1325
```

Is there a way to turn off dependency on pid/log file usage?

Is there a way to set a writable dir to be used instead of where Workerman is attempting to utilize?

**Comment by walkor** [comment]
> can I just turn this off completely to be able to operate in a read only environment?

Sorry, It not support turn off
