### ISSUE TITLE
Get status unserialize error

### ISSUE THREAD

**Issue by webrobot1** [walkor/workerman#889]
SAt file Worker.php in method formatStatusData  have code 

        ```
        $info = \file($statistics_file, \FILE_IGNORE_NEW_LINES);
        if (!$info) {
            return '';
        }
        $status_str = '';
        $current_total_request = array();
        $worker_info = \unserialize($info[0]);
        \ksort($worker_info, SORT_NUMERIC);
```

But some time situation like this 

array of $info is:

```
Log file
(
[0] => --------------------------------------------------------------------- WORKERMAN CONNECTION STATUS --------------------------------------------------------------------------------
[1] => PID Worker CID Trans Protocol ipv4 ipv6 Recv-Q Send-Q Bytes-R Bytes-W Status Local Address Foreign Address
[2] => 20788 6.01M websocket://0.0.0.0:8090 none 2 0 3 219
[3] => 20788 none 2 tcp Redis 1 0 0B 0B 1.5KB 1.7KB ESTABLISHED 127.0.0.1:60376 127.0.0.1:6379
[4] => 20788 none 3 tcp WsProtocol 1 0 0B 0B 22.7KB 110.1KB ESTABLISHED 127.0.0.1:57902 127.0.0.1:8081
)
```

And i get error :

```
TypeError: ksort(): Argument #1 ($array) must be of type array, bool given in /var/www/html/vendor/workerman/workerman/Worker.php:1068
Stack trace:
#0 /var/www/html/vendor/workerman/workerman/Worker.php(1068): ksort()
#1 /var/www/html/vendor/workerman/workerman/Worker.php(969): Workerman\Worker::formatStatusData()
#2 /var/www/html/vendor/workerman/workerman/Worker.php(552): Workerman\Worker::parseCommand()
#3 /var/www/html/app/server/model/CommandModel.php(68): Workerman\Worker::runAll()
#4 /var/www/html/core/Cli.php(47): Fantasy\App\server\model\CommandModel::status()
```

I think need replace 

`$worker_info = \unserialize($info[0]); `

 to 

```
if(!$worker_info = \unserialize($info[0])) 
{
	return;
}
```

**Comment by walkor** [comment]
var_dump($statistics_file) and find the path then remove the file by manually.

**Comment by webrobot1** [comment]
> var_dump($statistics_file) and find the path then remove the file by manually.

it is not one time error. it happen always if i get worker status every 10 seconds

**Comment by webrobot1** [comment]
i already delete many times and start again after some time it come again

**Comment by walkor** [comment]
Do you run `php start.php connections` every 10 seconds too?

**Comment by webrobot1** [comment]
> Refer

yes. after i get status next moment i get connections. i have few workers and ask about status and connections each
